module "shared_account_vpc" {
  source = "../../../modules/aws/network/vpc"

  cidr_block                        = var.shared_account_cidr_block
  enable_dns_support                = var.shared_account_enable_dns_support
  enable_dns_hostnames              = var.shared_account_enable_dns_hostnames
  common_tags                       = var.common_tags
  vpc_tags                          = var.vpc_tags
  vpc_resource_prefix               = var.vpc_resource_prefix
  environment_name                  = var.shared_account_environment_name
  enable_dhcp_options               = var.shared_account_enable_dhcp_options
  dhcp_options_domain_name          = var.shared_account_dhcp_options_domain_name
  dhcp_options_domain_name_servers  = var.shared_account_dhcp_options_domain_name_servers
  dhcp_options_ntp_servers          = var.shared_account_dhcp_options_ntp_servers
  dhcp_options_tags                 = var.dhcp_options_tags
  dhcp_options_resource_prefix      = var.dhcp_options_resource_prefix
  subnet_resource_prefix            = var.subnet_resource_prefix
  public_subnets                    = var.shared_account_public_subnets
  public_subnet_tags                = var.public_subnet_tags
  public_subnet_tier_name           = var.public_subnet_tier_name
  private_subnets                   = var.shared_account_private_subnets
  private_subnet_tags               = var.private_subnet_tags
  private_subnet_tier_name          = var.private_subnet_tier_name
  eks_cluster_resource_prefix       = var.eks_cluster_resource_prefix
  eks_cluster_tier_name             = var.eks_cluster_tier_name
  data_subnets                      = var.shared_account_data_subnets
  data_subnet_tags                  = var.data_subnet_tags
  data_subnet_tier_name             = var.data_subnet_tier_name
  db_subnet_group_resource_prefix   = var.db_subnet_group_resource_prefix
  db_subnet_group_tags              = var.db_subnet_group_tags
  default_network_acl_ingress_rules = var.shared_account_default_network_acl_ingress_rules
  default_network_acl_egress_rules  = var.shared_account_default_network_acl_egress_rules
  default_network_acl_tags          = var.default_network_acl_tags
  network_acl_resource_prefix       = var.network_acl_resource_prefix
  default_network_acl_tier_name     = var.default_network_acl_tier_name
  public_network_acl_ingress_rules  = var.shared_account_public_network_acl_ingress_rules
  public_network_acl_egress_rules   = var.shared_account_public_network_acl_egress_rules
  public_network_acl_tags           = var.public_network_acl_tags
  private_network_acl_ingress_rules = var.shared_account_private_network_acl_ingress_rules
  private_network_acl_egress_rules  = var.shared_account_private_network_acl_egress_rules
  private_network_acl_tags          = var.private_network_acl_tags
  data_network_acl_ingress_rules    = var.shared_account_data_network_acl_ingress_rules
  data_network_acl_egress_rules     = var.shared_account_data_network_acl_egress_rules
  data_network_acl_tags             = var.data_network_acl_tags
  internet_gateway_tags             = var.internet_gateway_tags
  internet_gateway_resource_prefix  = var.internet_gateway_resource_prefix
  eip_tags                          = var.eip_tags
  nat_eip_resource_prefix           = var.nat_eip_resource_prefix
  nat_eip_tier_name                 = var.nat_eip_tier_name
  nat_gateway_tags                  = var.nat_gateway_tags
  nat_gateway_resource_prefix       = var.nat_gateway_resource_prefix
  route_table_tags                  = var.route_table_tags
  route_table_resource_prefix       = var.route_table_resource_prefix

  providers = {
    aws = aws.shared
  }
}
